#!/bin/sh
PATH=$PATH:/usr/local/bin:/usr/local/sbin
. "$(dirname "$0")/_/husky.sh"

[ -n "$CI" ] && exit 0

# Format and submit code according to lintstagedrc.js configuration
npm run lint:lint-staged
